server:
  port: 80

security:
  basic:
    enabled: false


spring: 
  mail: 
    host: smtp.exmail.qq.com
    username: police@whalegoods.com
    password: Aa123456?
    properties:
      mail: 
        smtp: 
          auth: true
          starttls:
            enable: true
            required: true
  freemarker: 
    charset: UTF-8
    cache: false
    settings: 
      template_update_delay: 0
  profiles: 
    active: pro
  datasource: 
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' 
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  http:
      multipart: 
        enabled: false
      encoding:
        force: true

mybatis:
    type-aliases-package: com.whalegoods.entity
    mapper-locations: classpath*:mapper/*.xml
    check-config-location: true

mapper:
    mappers:
        - com.whalegoods.mapper
    not-empty: false
    identity: MYSQL


# PageHelperConfig 可以替代此方案
pagehelper:
    helperDialect: mysql
    reasonable: false
    offsetAsPageNum: true
    rowBoundsWithCount: true
    supportMethodsArguments: true
    params: count=countSql