spring: 
  datasource:
        url: jdbc:mysql://rm-wz94344lxtoa3m4m5.mysql.rds.aliyuncs.com:3306/whalegoods?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: whalegoods_rds
        password: WhaleGoods2018
  http:
      multipart: 
        location: /usr/local/erp/whalegoods-file/
        addr: http://erp.whalegoods.com/file/
logging:
  level:
      com.whalegoods.mapper: info 
  config: classpath:logback-spring.xml       