spring: 
  datasource:
        url: jdbc:mysql://rm-wz94344lxtoa3m4m59o.mysql.rds.aliyuncs.com:3306/whalegoods?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: whalegoods_rds
        password: WhaleGoods2018
  http:
      multipart: 
        location: D:/whalegoods-file/
        addr: http://127.0.0.1/file/
logging:
  level:
      com.whalegoods.mapper: debug
  config: classpath:logback-spring.xml