spring: 
  datasource:
        url: jdbc:mysql://rm-wz9rh2817r2e5l9b1ko.mysql.rds.aliyuncs.com:3306/whalegoods_release?useUnicode=true&characterEncoding=UTF-8
        username: whalegoods_rds
        password: WhaleGoods2018
  http:
      multipart: 
        location: D:/whalegoods-file/

logging:
  level:
      com.whalegoods.mapper: debug