server:
  port: 80

security:
  basic:
    enabled: false

spring:
  datasource:
        url: jdbc:mysql://rm-wz9rh2817r2e5l9b1ko.mysql.rds.aliyuncs.com:3306/whalegoods_release?useUnicode=true&characterEncoding=UTF-8
        username: whalegoods_rds
        password: WhaleGoods2018
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' 
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  http:
      encoding:
        force: true

mybatis:
    type-aliases-package: com.whalegoods.entity
    mapper-locations: classpath*:mapper/*.xml
    check-config-location: true

mapper:
    mappers:
        - com.len.base.BaseMapper
    not-empty: false
    identity: MYSQL


# PageHelperConfig 可以替代此方案
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level:
      com.len.mapper: debug